### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by dfyzicka** [soldatov-ss/flibusta-telegram-bot#4]
не получается запустить постоянно ругается на информацию из .env файла, я правильно понял что он должен в корне лежать?
использую как референс это:
ADMINS=admin_id
BOT_TOKEN=bot_token

SITE_PASS=password_for_flibusta
SITE_LOGIN=login_for_flibusta

DB_USER=postgres
DB_PASS=password
DB_HOST=localhost
DB_NAME=postgres

GROUP_ID=group_id
CHANNEL_ID=channel_id

только не понял можно ли не использовать GROUP_ID и CHANNEL_ID и зачем они нужны для работы бота самого по себе ?

**Comment by soldatov-ss** [comment]
да, в корне
CHANNEL_ID для постинга в канал
GROUP_ID для использования бота в группе, для ограничений
оба можно заккоментировать **в коде**

**Comment by soldatov-ss** [comment]
> не получается запустить постоянно ругается на информацию из .env файла, я правильно понял что он должен в корне лежать? использую как референс это: ADMINS=admin_id BOT_TOKEN=bot_token
> 
> SITE_PASS=password_for_flibusta SITE_LOGIN=login_for_flibusta
> 
> DB_USER=postgres DB_PASS=password DB_HOST=localhost DB_NAME=postgres
> 
> GROUP_ID=group_id CHANNEL_ID=channel_id
> 
> только не понял можно ли не использовать GROUP_ID и CHANNEL_ID и зачем они нужны для работы бота самого по себе ?



да, в корне
CHANNEL_ID для постинга в канал
GROUP_ID для использования бота в группе, для ограничений
оба можно заккоментировать в коде

**Comment by dfyzicka** [comment]
Благодарю.
