### ISSUE TITLE
Error on run docker compose

### ISSUE THREAD

**Issue by urtaevS** [soldatov-ss/flibusta-telegram-bot#5]
Get an error when run
`docker-compose up`

`  Downloading pip-24.2-py3-none-any.whl.metadata (3.6 kB)
ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install`

**Comment by soldatov-ss** [comment]
@urtaevS fixed in the latest commit **8fa18187**
Updated Docker file to:
```
RUN pip install --upgrade pip \
    && pip install -r /usr/src/app/bot/requirements.txt
```

**Comment by soldatov-ss** [comment]
@urtaevS if it helped you - please mark answer as accepted and close the issue.
Thanks

**Comment by urtaevS** [comment]
> @soldatov-ss 
Yes it's work for me!
Thank you!
