### ISSUE TITLE
Error after start the bot

### ISSUE THREAD

**Issue by urtaevS** [soldatov-ss/flibusta-telegram-bot#6]
` OperationalError: (pymysql.err.OperationalError) (1130, "Host '172.21.0.3' is not allowed to connect to this MySQL server")`

**Comment by soldatov-ss** [comment]
@urtaevS it seems you should create root user 
take a look
https://stackoverflow.com/questions/19101243/error-1130-hy000-host-is-not-allowed-to-connect-to-this-mysql-server

try something like this 
`docker exec -it <mysql_container_name> mysql -u root -p`
`GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;
FLUSH PRIVILEGES;`

**Comment by urtaevS** [comment]
> soldatov-ss

after this command 
`GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION; FLUSH PRIVILEGES;`

Get this:
`mysql> GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION; FLUSH PRIVILEGES;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'password' WITH GRANT OPTION' at line 1`

**Comment by soldatov-ss** [comment]
try to ceate the User (if it doesn't exist):
`CREATE USER 'mysql'@'%' IDENTIFIED BY 'password';`
And then grant Permissions:
```
GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
```

**Comment by urtaevS** [comment]
Now i get this
`sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'database.users' doesn't exist")`

**Comment by soldatov-ss** [comment]
@urtaevS just run migrations:
`docker-compose exec bot alembic upgrade head`

**Comment by urtaevS** [comment]
@soldatov-ss 
Same problem

`bot_1  | 2024-08-08 14:11:08,034 ERROR    [aiogram.event] (dispatcher.py:_process_update:315) Cause exception while process update id=775331303 by bot id=6878316197
bot_1  | ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'database.users' doesn't exist")
bot_1  | [SQL: INSERT INTO users (user_id, username, full_name, language) VALUES (%s, %s, %s, %s) AS new ON DUPLICATE KEY UPDATE username = %s, full_name = %s, language = %s]`

**Comment by soldatov-ss** [comment]
have you run the migrations?

**Comment by urtaevS** [comment]
Yes.
I'll try with clean install.
Do i need run only migration command, or i need create db user, grant permission and then make migration?

**Comment by soldatov-ss** [comment]
@urtaevS just run migrations, it should work, and then download from flibusta dumps and restore database, see README.me in dumps folder
